# Generated by Django 4.0.5 on 2022-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_user_id', models.IntegerField(null=True)),
                ('second_user_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='There is nothing yet...', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2000-12-01'),
        ),
    ]
